/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InputFieldResponse } from './InputFieldResponse.ts'

/**
 * @description Base serializer for all models.
 */
export type FormResponse = {
  /**
   * @type integer
   */
  readonly id: number
  /**
   * @type array
   */
  response_fields: InputFieldResponse[]
  /**
   * @type string, date-time
   */
  readonly created_at: string
  /**
   * @type string, date-time
   */
  readonly updated_at: string
  /**
   * @type integer
   */
  created_by?: number | null
  /**
   * @type integer
   */
  updated_by?: number | null
  /**
   * @type integer
   */
  form_assignment: number
}